In [1]:
import itertools


In [6]:
import itertools
import numpy as np

# Resource constraints
resources_c1 = 0.5
resources_c2 = 0.4
resources_c3 = 0.4

#rewards in det
r_11_p=1
r_12_p=4
r_21_p=0.9
r_31_p=1.25
r_32_p=5
r_11_o=0.2
r_12_o=0.35
r_21_o=0.3
r_31_o=0.25
r_32_o=0.4



rewards=[r_11_p, r_12_p, r_21_p, r_31_p, r_32_p, r_11_o, r_12_o, r_21_o, r_31_o, r_32_o]
# Task resource requirements
k1_resource = 0.1
k2_resource = 0.2

# Arrival rates
lambda_1 = 3.51
lambda_2 = 1.17


# Service rates
mu_1 = 0.9
mu_2 = 0.3


# Maximum possible number of tasks for each cloud provider based on resources
max_tasks_c1_k1 = int(resources_c1 / k1_resource)
max_tasks_c1_k2 = int(resources_c1 / k2_resource)
max_tasks_c2_k1 = int(resources_c2 / k1_resource)
max_tasks_c2_k2 = int(resources_c2 / k2_resource)
max_tasks_c3_k1 = int(resources_c3 / k1_resource)
max_tasks_c3_k2 = int(resources_c3 / k2_resource)

# Generate all possible states
valid_states = []
#a dictionary used to get the index of the state given the state itself
state_indices = {}
index = 0

for S_11, S_12, S_21, S_31,S_32 in itertools.product(range(max_tasks_c1_k1 + 1),
                                                 range(max_tasks_c1_k2 + 1),
                                                 range(max_tasks_c2_k1 + 1),
                                                 range(max_tasks_c3_k1 + 1),
                                                 range(max_tasks_c3_k2 + 1)):
    # Calculate resource consumption for each cloud
    c1_usage = S_11 * k1_resource + S_12 * k2_resource
    c2_usage = S_21 * k1_resource
    c3_usage = S_31 * k1_resource + S_32 * k2_resource

    # Check if resource usage is within the limits
    #if the resources of the generated combination is valid then add it to the valid states
    if c1_usage <= resources_c1 and c2_usage <= resources_c2 and c3_usage <= resources_c3:
        state = (S_11, S_12, S_21, S_31, S_32)
        valid_states.append(state)
        state_indices[state] = index
        index += 1

num_states = len(valid_states)

# Output the valid states
print("Valid states are:")
for state in valid_states:
    print(state)


Valid states are:
(0, 0, 0, 0, 0)
(0, 0, 0, 0, 1)
(0, 0, 0, 0, 2)
(0, 0, 0, 1, 0)
(0, 0, 0, 1, 1)
(0, 0, 0, 2, 0)
(0, 0, 0, 2, 1)
(0, 0, 0, 3, 0)
(0, 0, 0, 4, 0)
(0, 0, 1, 0, 0)
(0, 0, 1, 0, 1)
(0, 0, 1, 0, 2)
(0, 0, 1, 1, 0)
(0, 0, 1, 1, 1)
(0, 0, 1, 2, 0)
(0, 0, 1, 2, 1)
(0, 0, 1, 3, 0)
(0, 0, 1, 4, 0)
(0, 0, 2, 0, 0)
(0, 0, 2, 0, 1)
(0, 0, 2, 0, 2)
(0, 0, 2, 1, 0)
(0, 0, 2, 1, 1)
(0, 0, 2, 2, 0)
(0, 0, 2, 2, 1)
(0, 0, 2, 3, 0)
(0, 0, 2, 4, 0)
(0, 0, 3, 0, 0)
(0, 0, 3, 0, 1)
(0, 0, 3, 0, 2)
(0, 0, 3, 1, 0)
(0, 0, 3, 1, 1)
(0, 0, 3, 2, 0)
(0, 0, 3, 2, 1)
(0, 0, 3, 3, 0)
(0, 0, 3, 4, 0)
(0, 0, 4, 0, 0)
(0, 0, 4, 0, 1)
(0, 0, 4, 0, 2)
(0, 0, 4, 1, 0)
(0, 0, 4, 1, 1)
(0, 0, 4, 2, 0)
(0, 0, 4, 2, 1)
(0, 0, 4, 3, 0)
(0, 0, 4, 4, 0)
(0, 1, 0, 0, 0)
(0, 1, 0, 0, 1)
(0, 1, 0, 0, 2)
(0, 1, 0, 1, 0)
(0, 1, 0, 1, 1)
(0, 1, 0, 2, 0)
(0, 1, 0, 2, 1)
(0, 1, 0, 3, 0)
(0, 1, 0, 4, 0)
(0, 1, 1, 0, 0)
(0, 1, 1, 0, 1)
(0, 1, 1, 0, 2)
(0, 1, 1, 1, 0)
(0, 1, 1, 1, 1)
(0, 1, 1, 2, 0)
(0, 1, 1, 2, 1)
(0, 1,

In [7]:
#a function to generate all different combination of 1s and 0s of certain length
def generate_combinations(length):
    # Create an array of 0s and 1s
    array = [0, 1]
    # Use itertools.product to generate all combinations
    combinations = list(itertools.product(array, repeat=length))
    return combinations

actions_indeces={}
combinations=generate_combinations(10)
#possible actions are the set of actions that you can take, it takes the form of (a_11_p, a_12_p, a_21_p, a_31_p, a_32_p, a_11_o, a_12_o, a_21_o, a_31_o, a_32_o)
possible_actions=[]
i=0
for combination in combinations:
    #this if conditions means that for a set of action to be valid, it has to decide what to do with both task 1 and task 2
    # it cant allocate a task to more than one provider or more than one method (provisioned or on-demand)
    #if it passes the checks, then it is a valid action
    if combination[0]+combination[2]+combination[3]+combination[5]+combination[7]+combination[8] == 1:
        if combination[1]+combination[4]+combination[6]+combination[9] ==1:
            possible_actions.append(combination)
            actions_indeces[combination]=i
            i=i+1

for action in possible_actions:
    print(action)




(0, 0, 0, 0, 0, 0, 0, 0, 1, 1)
(0, 0, 0, 0, 0, 0, 0, 1, 0, 1)
(0, 0, 0, 0, 0, 0, 1, 0, 1, 0)
(0, 0, 0, 0, 0, 0, 1, 1, 0, 0)
(0, 0, 0, 0, 0, 1, 0, 0, 0, 1)
(0, 0, 0, 0, 0, 1, 1, 0, 0, 0)
(0, 0, 0, 0, 1, 0, 0, 0, 1, 0)
(0, 0, 0, 0, 1, 0, 0, 1, 0, 0)
(0, 0, 0, 0, 1, 1, 0, 0, 0, 0)
(0, 0, 0, 1, 0, 0, 0, 0, 0, 1)
(0, 0, 0, 1, 0, 0, 1, 0, 0, 0)
(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 1, 0, 0, 0, 0, 0, 0, 1)
(0, 0, 1, 0, 0, 0, 1, 0, 0, 0)
(0, 0, 1, 0, 1, 0, 0, 0, 0, 0)
(0, 1, 0, 0, 0, 0, 0, 0, 1, 0)
(0, 1, 0, 0, 0, 0, 0, 1, 0, 0)
(0, 1, 0, 0, 0, 1, 0, 0, 0, 0)
(0, 1, 0, 1, 0, 0, 0, 0, 0, 0)
(0, 1, 1, 0, 0, 0, 0, 0, 0, 0)
(1, 0, 0, 0, 0, 0, 0, 0, 0, 1)
(1, 0, 0, 0, 0, 0, 1, 0, 0, 0)
(1, 0, 0, 0, 1, 0, 0, 0, 0, 0)
(1, 1, 0, 0, 0, 0, 0, 0, 0, 0)


In [8]:

#this few lines of code are used to generate the transition rates matrices

transition_rates = np.zeros((num_states, num_states))



# Build the transition rate matrix
for current_state in valid_states:
    current_index = state_indices[current_state]
    S_11, S_12, S_21, S_31, S_32 = current_state

    # Calculate departure rates from each state
    if S_11 > 0:
        next_state = (S_11 -1, S_12, S_21, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            rate = mu_1
            transition_rates[current_index, next_index] += S_11 * rate
    if S_12 > 0:
        next_state = (S_11, S_12-1, S_21, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            rate = mu_2
            transition_rates[current_index, next_index] += S_12 * rate
    if S_21 > 0:
        next_state = (S_11, S_12, S_21-1, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            rate = mu_1
            transition_rates[current_index, next_index] += S_21 * rate
    if S_31 > 0:
        next_state = (S_11, S_12, S_21, S_31-1, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            rate = mu_1
            transition_rates[current_index, next_index] += S_31 * rate
    if S_32 > 0:
        next_state = (S_11, S_12, S_21, S_31, S_32-1)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            rate = mu_2
            transition_rates[current_index, next_index] += S_32 * rate


    # Calculate arrival rates
    # Task type k1 arrival

    #  allocate to C1 provisioned resources
    new_S_11 = S_11 + 1
    c1_usage = new_S_11 * k1_resource + S_12 * k2_resource
    if c1_usage <= resources_c1:
        next_state = (new_S_11, S_12, S_21, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            transition_rates[current_index, next_index] += lambda_1


    # On-demand allocation (state does not change)
    transition_rates[current_index, current_index] += lambda_1


    # Try to allocate to C2 provisioned resources
    new_S_21 = S_21 + 1
    c2_usage = new_S_21 * k1_resource
    if c2_usage <= resources_c2:
        next_state = (S_11, S_12, new_S_21, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            transition_rates[current_index, next_index] += lambda_1


    # On-demand allocation (state does not change)
    transition_rates[current_index, current_index] += lambda_1

    # Try to allocate to C3 provisioned resources
    new_S_31 = S_31 + 1
    c3_usage = new_S_31 * k1_resource + S_32 * k2_resource
    if c3_usage <= resources_c3:
        next_state = (S_11, S_12, S_21, new_S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            transition_rates[current_index, next_index] += lambda_1


    # On-demand allocation (state does not change)
    transition_rates[current_index, current_index] += lambda_1


# Task type k2 arrival


    # Try to allocate to C1 provisioned resources
    new_S_12 = S_12 + 1
    c1_usage = S_11 * k1_resource + new_S_12 * k2_resource
    if c1_usage <= resources_c1:
        next_state = (S_11, new_S_12, S_21, S_31, S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            transition_rates[current_index, next_index] += lambda_2



    # On-demand allocation (state does not change)
    transition_rates[current_index, current_index] += lambda_2



    # Try to allocate to C3 provisioned resources
    new_S_32 = S_32 + 1
    c3_usage = S_31 * k1_resource + new_S_32 * k2_resource
    if c3_usage <= resources_c3:
        next_state = (S_11, S_12, S_21, S_31, new_S_32)
        next_index = state_indices.get(next_state)
        if next_index is not None:
            transition_rates[current_index, next_index] += lambda_2


    # On-demand allocation (state does not change)
    transition_rates[current_index, current_index] += lambda_2

    total_rate = np.sum(transition_rates[current_index, :])


# Output the transition rate matrix
print("Transition Rate Matrix (Generator Matrix):")
print(transition_rates)


Transition Rate Matrix (Generator Matrix):
[[12.87  1.17  0.   ...  0.    0.    0.  ]
 [ 0.3  12.87  1.17 ...  0.    0.    0.  ]
 [ 0.    0.6  12.87 ...  0.    0.    0.  ]
 ...
 [ 0.    0.    0.   ... 12.87  0.    0.  ]
 [ 0.    0.    0.   ...  0.   12.87  3.51]
 [ 0.    0.    0.   ...  0.    3.6  12.87]]


In [9]:
#simplified the uniformizatrion more than the description
row_sums = transition_rates.sum(axis=1, keepdims=True)  # Get the sum of each row
transition_probs = transition_rates / row_sums  # Divide each element by its row sum

print(transition_probs)

[[0.5        0.04545455 0.         ... 0.         0.         0.        ]
 [0.01152074 0.49423963 0.04493088 ... 0.         0.         0.        ]
 [0.         0.02770083 0.59418283 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.55786736 0.         0.        ]
 [0.         0.         0.         ... 0.         0.47350993 0.12913907]
 [0.         0.         0.         ... 0.         0.14652015 0.52380952]]


In [10]:
#this function when given an action, it returns the possible next states, which is a dectionary which has as key the next key and the value (transition_probability, reward)
#as an example
# {(0,0,0,1):(0.35,4)}
def transition(state,action):
    possible_next_states={}
    state=list(state)
    for i in range(len(action)):
        state=list(state)
        # remember action is in the form of (a_11_p, a_12_p, a_21_p, a_31_p, a_32_p, a_11_o, a_12_o, a_21_o, a_31_o, a_32_o)
        #the first 5 elements of action are the ones that result in state change (provisioned resources)
        # all actions are expected to have two ones and the rest are zeros
        if i<5:
            if action[i]==1:
                next_state=state.copy()

                next_state[i]=next_state[i]+1
                next_state=tuple(next_state)
                state=tuple(state)
                if state_indices.get(next_state) is not None:

                    possible_next_states[next_state]=(transition_probs[state_indices.get(state),state_indices.get(next_state)],rewards[i])


        else:
            if action[i]==1:
                state=tuple(state)
                next_state=state
                #if the action is on demand, just devide by a large number from simplification
                possible_next_states[next_state]=(transition_probs[state_indices.get(state),state_indices.get(next_state)],rewards[i]/100)
    return possible_next_states


In [11]:
def value_iteration():
    value_table = np.zeros(num_states) #value table
    policy=np.zeros(num_states)# Initialize value function
    gamma = 0.9  # Discount factor
    theta = 1e-6  # Convergence threshold
    while True:
        delta = 0
        #loop over all valid fields
        for state in valid_states:

            v = value_table[state_indices.get(state)]
            action_values = []
            #for each state , loop over all possible actions
            for action in possible_actions:
                action_value=0
                possible_next_states = transition(state, action)
                #if the transition return an empty dictionary, this means this action is not valid for this state, put the action value to be a negative value (very low reward)
                if possible_next_states =={}:
                    action_values.append(-3)
                    continue
                #bellman equation
                for next_state in possible_next_states:
                    action_value += possible_next_states[next_state][0]*(possible_next_states[next_state][1] + gamma * value_table[state_indices.get(next_state)])


                action_values.append(action_value)
            #update value table with the max action value
            value_table[state_indices.get(state)] = np.max(action_values)
            # update policy with the best action for this state
            policy[state_indices.get(state)]=np.argmax(action_values)
            #check the delta for convergence
            delta = max(delta, abs(v - value_table[state_indices.get(state)]))
            print(delta)
        if delta < theta:

            break
    return value_table,policy

v_table,policy=value_iteration()

0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727272728
0.3977272727

In [12]:
for i in range(len(policy)):
    print(valid_states[i],' prefers',possible_actions[int(policy[i])])
    

(0, 0, 0, 0, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 0, 0, 1)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 0, 0, 2)  prefers (0, 1, 0, 0, 0, 0, 0, 1, 0, 0)
(0, 0, 0, 1, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 0, 1, 1)  prefers (0, 1, 0, 1, 0, 0, 0, 0, 0, 0)
(0, 0, 0, 2, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 0, 2, 1)  prefers (0, 1, 0, 0, 0, 0, 0, 1, 0, 0)
(0, 0, 0, 3, 0)  prefers (0, 1, 0, 1, 0, 0, 0, 0, 0, 0)
(0, 0, 0, 4, 0)  prefers (1, 1, 0, 0, 0, 0, 0, 0, 0, 0)
(0, 0, 1, 0, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 1, 0, 1)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 1, 0, 2)  prefers (0, 1, 0, 0, 0, 0, 0, 1, 0, 0)
(0, 0, 1, 1, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 1, 1, 1)  prefers (0, 1, 0, 1, 0, 0, 0, 0, 0, 0)
(0, 0, 1, 2, 0)  prefers (0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
(0, 0, 1, 2, 1)  prefers (0, 1, 0, 0, 0, 0, 0, 1, 0, 0)
(0, 0, 1, 3, 0)  prefers (0, 1, 0, 1, 0, 0, 0, 0, 0, 0)
(0, 0, 1, 4, 0)  prefers (1, 1, 0, 0, 0, 0, 0, 0